name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy==1.16.2
  - matplotlib==3.0.3
  - trackpy==0.4.2
  - pims==0.5
  - pandas==0.24.2
  - scipy==1.2.1
  - scikit-image==0.14.2
  - ipython==7.4.0
  - ipywidgets==7.4.2
  - jupyter_contrib_nbextensions
